### ISSUE TITLE
Use mojang-mappings for Reflection

### ISSUE THREAD

**Issue by aj-rom** [CoachLuck/BackPacksPlus#22]
With the update to 1.17 classes used for reflection were obfuscated, read more on this [here](https://www.spigotmc.org/threads/spigot-bungeecord-1-17.510208/). 

The issue is that our reflection classes (1.16 and below) rely on the mapped names spigot provided for us, for example *ItemStack* which will now be an obfuscated form of a specific id of the nms copy. You can read more on the differences [here](https://www.spigotmc.org/wiki/spigot-nms-and-minecraft-versions-1-16/).

**1.17 will not be able to work without this being updated**

Utilizing the mojang mappings and then forcing maven to rename on compile is most likely the best route to take.

This effects our DisplayItemHelper as we are using the names NBT components when they need to be converted to the obfuscated form.

**Comment by BrainStone** [comment]
You could possibly use https://www.spigotmc.org/resources/nbt-api.7939/ if all you're using NMS for is the NBT stuff.
