### ISSUE TITLE
What am I doing wrong? t

### ISSUE THREAD

**Issue by TheLilStiles** [CoachLuck/BackPacksPlus#3]
tried adding a new backpack with my friends name, the plugin worked before I messed around the config. I tried to add a new backpack through the config and now when I do /backpack the recipes arent there and I cant craft any backpack. Ill type the code  and I would really wanna know what I did wrong.

# BackPacks+ by CoachL_ck
# Information: https://github.com/CoachLuck/BackPacksPlus
# PLAYER_HEAD Textures: https://minecraft-heads.com/
# Please do not change Config-Version
# To add backpacks just copy a section, for example "BackPacks.Basic" or "BackPacks.Advanced"
# Then paste at the bottom, and rename to "BackPacks.NewName"
# For example:
# BackPacks:
#    Basic:
#      Name: "Some Name"
#      
#    NewName:
#      Name: "Some Name"
#      
Config-Version: 2
Check-For-Update: true
General:
  BackPackLimiter:
    Enabled: false
    Repeat: 20
BackPacks:
  Basic:
    Name: "&c&lBackPack+"
    Title: "&e&lBackPack"
    Material: "PLAYER_HEAD"
    Texture: "http://textures.minecraft.net/texture/8351e505989838e27287e7afbc7f97e796cab5f3598a76160c131c940d0c5"
    CustomData:
    Lore:
      - "&8&m                                      "
      - " &7Click me to open this &dBackPack"
      - "&8&m                                      "
    Enchanted: true
    Size: 9
    Recipe:
      Shape:
        - "LLL"
        - "LCL"
        - "LLL"
      Materials:
        L:
          Material: "LEATHER"
        C:
          Material: "CHEST"
  Advanced:
    Name: "&e&lAdvanced &c&lBackPack+"
    Title: "&e&lAdvanced&c&lBackPack"
    Material: "CLOCK"
    Texture: ""
    CustomData:
    Lore:
      - "&8&m                                      "
      - " &7Click me to open this &dBackPack"
      - "&8&m                                      "
    Enchanted: true
    Size: 18
    Recipe:
      Shape:
        - "GGG"
        - "GCG"
        - "GGG"
      Materials:
        G:
          Material: "GOLD_BLOCK"
        C:
          Material: "CHEST"
  Mega:
    Name: "&b&lMega &c&lBackPack+"
    Title: "&b&lMega&c&lBackPack"
    Material: "PLAYER_HEAD"
    Texture: "http://textures.minecraft.net/texture/df70fab3246fe027ce0bba885a73c6e82d8ff8f358231e8461f956560cfa58f"
    CustomData:
    Lore:
      - "&8&m                                      "
      - " &7Click me to open this &dBackPack"
      - "&8&m                                      "
    Enchanted: true
    Size: 27
    Recipe:
      Shape:
        - "DDD"
        - "DCD"
        - "DDD"
      Materials:
        D:
          Material: "DIAMOND_BLOCK"
        C:
          Material: "CHEST"         
  Mostafa:
      Name: "&2&lMostafa &c&lBackPack+"
      Title: "&2&lMostafa &c&lBackPack"
      Material: "PLAYER_HEAD"
      Texture: "http://textures.minecraft.net/texture/a87fdf4587a6449bfc8be33ab2e938e36bf05e40f6faa277d71b50bcb0ea6838"
      CustomData:
      Lore:
       - "&8&m                        "
       - " &7Click me to open this &dBackPack"
       - "&8&m                        "
   Enchanted: true
   Size: 4
   Recipe:
     Shape:
       - "KKK"
       - "KCK"
       - "KKK"
     Materials:
        K:
          Material: "CACTUS"
        C:
          Material: "CHEST"

**Comment by Maulwurf38** [comment]
Try to change the size of lMostafa to 9 ^^
i think this could be the Problem

**Comment by TheLilStiles** [comment]
> Try to change the size of lMostafa to 9 ^^
> i think this could be the Problem

I just tried it and it did nothing, same result. Im confused

**Comment by aj-rom** [comment]
@TheLilStiles The size must be 9, 18, 27, 36, or 45. Please attach the whole config.yml file so I can trouble shoot this further as well as any console errors that are logged.

**Comment by TheLilStiles** [comment]
> @TheLilStiles The size must be 9, 18, 27, 36, or 45. Please attach the whole config.yml file so I can trouble shoot this further as well as any console errors that are logged.

I reset the config yesterday so I could still get backpacks but today I rewrote that code for my friend and it worked. I put the size at 9 and it worked. I'm not sure if the problem was with the size or maybe I just had the formula wrong. I think its the latter. Anyways, will you ever add more size choices? I'd like to have larger and smaller backpacks :(

**Comment by aj-rom** [comment]
I am hoping to work on this some more in the upcoming months and am looking to add a feature that would allow backpacks of any size, although would need a cap of some sort to limit the amount of data stored within the item itself. So as a short answer, **yes**, this will be implemented in the future.
