### ISSUE TITLE
gold backpack texture

### ISSUE THREAD

**Issue by davofwater** [CoachLuck/BackPacksPlus#5]
the gold backpack looks like a compass. The textures for the leather and diamond ones look like backpacks.

**Comment by aj-rom** [comment]
Your config.yml should have something like this under each backpack if you want to use custom textures.

```Yaml
  Material: "CUSTOM"
  Texture: "http://textures.minecraft.net/texture/a3c153c391c34e2d328a60839e683a9f82ad3048299d8bc6a39e6f915cc5a"
```

If you need further help please join the discord or view the wiki.
