### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by davofwater** [CoachLuck/BackPacksPlus#6]
I have the plug-in installed properly and I can use it. But the other people on the server can't create or use. I looked up the section on wiki under permissions but I don't know where/how to enter this command --->   backpack.<craft/use>.*

I am obviously new to this and would love to use the plug-in on my server. Please help. thanks

**Comment by aj-rom** [comment]
Hey dav, you need a permissions plugin to be able to set permissions of a player. I suggest [LuckPerms](https://luckperms.net/).

**Comment by aj-rom** [comment]
@davofwater Still need help or can I close this issue?

**Comment by davofwater** [comment]
All set thank you. 

Sent from Yahoo Mail on Android 
 
  On Mon, Jan 18, 2021 at 12:09 PM, A.J. Romaniello<notifications@github.com> wrote:   


@davofwater Still need help or can I close this issue?
